[package]
name = "lrail-format-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
lrail-format = { path = "../crates/lrail-format" }
serde_json = "1"
tempfile = "3"

[[bin]]
name = "package_open"
path = "fuzz_targets/package_open.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
